config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  apipie
  get '/home', to: 'home#index', as: 'home'
  root to: redirect('/home')

  resources :avatar, only:[:edit, :update, :destroy]
  resources :users, only:[:edit, :update]
  # resources :books, only:[:new, :create, :show, :destroy]
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get '/student/sign_in', to: 'users/sessions#new'
    post '/student/sign_in', to: 'users/sessions#create', as: 'new_student_registration'
  end

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
  
  # resources :student, only: [:new, :create]
  # resources :tags, only: [:new, :create, :destroy]

  # get '/student_list', to: 'student#list', as: 'student_list'
  # get '/student/active', to: 'student#active', as: 'active'
  # put '/student/:id/suspend', to: 'student#suspend_student', as: 'suspend_student'
  # get '/student/suspended', to: 'student#suspended_student', as: 'suspended_student'
  # post '/student/:id/reactivation', to: 'student#send_reactivation_mail', as: 'send_reactivation_mail'
  # get '/student/:id/reactivate', to: 'student#reactivate_student', as: 'reactivate_student'
  # get '/book_list', to: 'books#list', as: 'book_list'
  # put '/book/:id/archive', to: 'books#archive', as: 'book_archive'
  # get '/tags_list', to: 'tags#list', as: 'tag_list'
  # post '/book/:id/issue', to: 'books#issue', as: 'book_issue'
  # put '/book/:id/like', to: 'books#like', as: 'book_like'
  # get '/book/issued_list', to: 'books#issued_list', as: 'issued_list'
  # put '/book/:id/return', to: 'books#return', as: 'return_book'
  # get 'book/:id/preview', to: 'books#preview', as: 'preview_book'

  resources :student, only: [:new, :create] do
    collection do
      get :student_list, action: :list, as: :student_list
      get :active, action: :active, as: :active
      get :suspended_student, action: :suspended_student, as: :suspended_student
    end
    
    member do
      put :suspend_student, as: :suspend_student
      post :send_reactivation_mail, as: :send_reactivation_mail
      get :reactivate_student, action: :reactivate_student, as: :reactivate_student
    end
  end
  
  resources :books, only: [:new, :create, :show, :destroy] do
    collection do
      get :book_list, action: :list, as: :book_list
      get :issued_list, action: :issued_list, as: :issued_list
    end
  
    member do
      put :archive, as: :archive, as: :book_archive
      post :issue, as: :issue, as: :book_issue
      put :like, as: :like, as: :book_like
      put :return, as: :return, as: :return_book
      get :preview, as: :preview, as: :preview_book
    end
  end
  
  resources :tags, only: [:new, :create, :destroy] do
    collection do
      get :tag_list, action: :list, as: :tag_list
    end
  end
  
  
  
  
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
    # before_action :set_student, only: []

    def list
        @student = User.where(:role_type=>1)

        if params[:filter]=="active"
            @student=@student.where(:status=>1)
        elsif params[:filter]=="suspended"
            @student=@student.where(:status=>2)
        end

        if params[:sort].present?
            sort_column=params[:sort] || "id"
            sort_direction = %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
            # sort_direction= params[:direction] || "desc"
            @student=@student.order(Arel.sql("#{sort_column} #{sort_direction}"))
        end
        @student=@student.paginate(page: params[:page], per_page: 10)
    end

    def new
        @student=User.new
    end

    def create
        @student=User.new(student_params)
        @student.password=SecureRandom.alphanumeric(8)
        
        if @student.save
            StudentMailer.with(user: @student).registration_mail.deliver_now
            redirect_to root_path, notice: "Student #{@student.first_name} is registered to the library successfully"
        else
            render :new
        end
    end

    def student_params
        params.require(:user).permit(:first_name, :last_name, :age, :date_of_birth, :email)
    end

    def active
        @student = User.where(:role_type=>1)
        @student=@student.where(:status=>1)
        if params[:sort].present?
            sort_column=params[:sort]
            sort_direction=params[:direction] || "desc"
            @student=@student.order("#{sort_column} #{sort_direction}")
        end
        @student=@student.paginate(page: params[:page], per_page: 10)
    end

    def suspend_student
        @student=User.find(params[:id])
        if @student.suspend!
            redirect_to active_student_index_path , notice:"Student suspended successfully!"
        else
            redirect_to active_student_index_path , notice:"Student not suspended"
        end
    end

    def suspended_student
        @student = User.where(:role_type=>1)
        @student=@student.where(:status=>2)
        # sort_column = params[:sort] || "id"
        # @student = @student.where(status: "suspended").order(sort_column).paginate(page: params[:page], per_page: 10)
        if params[:sort].present?
            sort_column=params[:sort]
            sort_direction=params[:direction] || "desc"
            @student=@student.order("#{sort_column} #{sort_direction}")
        end
        @student=@student.paginate(page: params[:page], per_page: 10)
    end

    def send_reactivation_mail
        @student=User.find(params[:id])
        StudentMailer.with(user: @student).reactivation_mail.deliver_now
        redirect_to suspended_student_student_index_path, notice: "Reactivation mail sent"
    end

    def reactivate_student
        @student=User.find(params[:id])
        if @student.reactivate!
            redirect_to root_path, notice: "Now you can login"
        end
    end
end

app/helpers/student_helper.rb
module StudentHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        direction = (column == params[:sort] && params[:direction] == "desc") ? "asc" : "desc"
        link_to title, { sort: column, direction: direction, filter: params[:filter] }, { class: "sortable" }
      end
end

app/views/student/active.html.haml
%br

%center.h1.center Active students

%table.table
    %thead.table
        %tr
            %th
                = link_to "Id", :sort => "id", direction: params[:sort] == "id" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "First Name", :sort => "first_name", direction: params[:sort] == "first_name" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Last Name", :sort => "last_name", direction: params[:sort] == "last_name" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Email", :sort => "email", direction: params[:sort] == "email" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Status", :sort => "status", direction: params[:sort] == "status" && params[:direction] == "asc" ? "desc" : "asc"
            %th
        - @student.each do |student|
            %tr
                %td
                    = student.id
                %td
                    = student.first_name
                %td
                    = student.last_name
                %td
                    = student.email
                %td
                    = student.status
                %td
                    = button_to "Suspend", suspend_student_student_path(student), method: :put, class: "btn btn-dark"
= will_paginate @students

app/views/student/list.html.haml
%br

%center.h1.center All students

= form_tag student_list_student_index_path, method: :get do
    = select_tag :filter, options_for_select([["All students", nil], ["Active students", "active"], ["Suspended students", "suspended"]], params[:filter])
    = submit_tag "Filter"

%table.table
    %thead.table
        %tr
            %th 
                = sortable "Id", "id"
                = link_to "Id", :sort => "id", direction: params[:sort] == "id" && params[:direction] == "asc" ? "desc" : "asc"
            %th 
                = sortable "first_name"
                = link_to "First Name", :sort => "first_name", direction: params[:sort] == "first_name" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = sortable "last_name"
                = link_to "Last Name", :sort => "last_name", direction: params[:sort] == "last_name" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = sortable "email"
                = link_to "Email", :sort => "email", direction: params[:sort] == "email" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = sortable "status"
                = link_to "Status", :sort => "status", direction: params[:sort] == "status" && params[:direction] == "asc" ? "desc" : "asc"
            %th
        - @student.each do |student|
            %tr
                %td
                    = student.id
                %td
                    = student.first_name
                %td
                    = student.last_name
                %td
                    = student.email
                %td
                    = student.status
= will_paginate @students

app/views/student/new.html.haml
%h2 Sign up
= form_for(@student, url: student_index_path, method: :post) do |f|
  .field
    = f.label :first_name
    %br/
    = f.text_field :first_name, autofocus: true, autocomplete: "first_name"
  .field
    = f.label :last_name
    %br/
    = f.text_field :last_name, autofocus: true, autocomplete: "last_name"
  .field
    = f.label :age
    %br/
    = f.number_field :age, autofocus: true, autocomplete: "age"
  .field
    = f.label :date_of_birth
    %br/
    = f.date_field :date_of_birth, autofocus: true, autocomplete: "date_of_birth"
  .field
    = f.label :email
    %br/
    = f.email_field :email, autofocus: true, autocomplete: "email"
  .actions
    = f.submit "Sign up"

app/views/student/suspended_student.html.haml
%br

%center.h1.center Suspended students

%table.table
    %thead.table
        %tr
            %th
                = link_to "Id", :sort => "id", direction: params[:sort] == "id" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "First Name", :sort => "first_name", direction: params[:sort] == "first_name" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Last Name", :sort => "last_name", direction: params[:sort] == "last_name" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Email", :sort => "email", direction: params[:sort] == "email" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Status", :sort => "status", direction: params[:sort] == "status" && params[:direction] == "asc" ? "desc" : "asc"
            %th
        - @student.each do |student|
            %tr
                %td
                    = student.id
                %td
                    = student.first_name
                %td
                    = student.last_name
                %td
                    = student.email
                %td
                    = student.status
                %td
                    = button_to "Reactivate", send_reactivation_mail_student_path(student), method: :post, class: "btn btn-dark"
= will_paginate @students