config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  apipie
  get '/home', to: 'home#index', as: 'home'
  root to: redirect('/home')

  resources :avatar, only:[:edit, :update, :destroy]
  resources :users, only:[:edit, :update]
  # resources :books, only:[:new, :create, :show, :destroy]
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get '/student/sign_in', to: 'users/sessions#new'
    post '/student/sign_in', to: 'users/sessions#create', as: 'new_student_registration'
  end

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
  
  # resources :student, only: [:new, :create]
  # resources :tags, only: [:new, :create, :destroy]

  # get '/student_list', to: 'student#list', as: 'student_list'
  # get '/student/active', to: 'student#active', as: 'active'
  # put '/student/:id/suspend', to: 'student#suspend_student', as: 'suspend_student'
  # get '/student/suspended', to: 'student#suspended_student', as: 'suspended_student'
  # post '/student/:id/reactivation', to: 'student#send_reactivation_mail', as: 'send_reactivation_mail'
  # get '/student/:id/reactivate', to: 'student#reactivate_student', as: 'reactivate_student'
  # get '/book_list', to: 'books#list', as: 'book_list'
  # put '/book/:id/archive', to: 'books#archive', as: 'book_archive'
  # get '/tags_list', to: 'tags#list', as: 'tag_list'
  # post '/book/:id/issue', to: 'books#issue', as: 'book_issue'
  # put '/book/:id/like', to: 'books#like', as: 'book_like'
  # get '/book/issued_list', to: 'books#issued_list', as: 'issued_list'
  # put '/book/:id/return', to: 'books#return', as: 'return_book'
  # get 'book/:id/preview', to: 'books#preview', as: 'preview_book'

  resources :student, only: [:new, :create] do
    collection do
      get :student_list, action: :list, as: :student_list
      get :active, action: :active, as: :active
      get :suspended_student, action: :suspended_student, as: :suspended_student
    end
    
    member do
      put :suspend_student, as: :suspend_student
      post :send_reactivation_mail, as: :send_reactivation_mail
      get :reactivate_student, action: :reactivate_student, as: :reactivate_student
    end
  end
  
  resources :books, only: [:new, :create, :show, :destroy] do
    collection do
      get :book_list, action: :list, as: :book_list
      get :issued_list, action: :issued_list, as: :issued_list
    end
  
    member do
      put :archive, as: :archive, as: :book_archive
      post :issue, as: :issue, as: :book_issue
      put :like, as: :like, as: :book_like
      put :return, as: :return, as: :return_book
      get :preview, as: :preview, as: :preview_book
    end
  end
  
  resources :tags, only: [:new, :create, :destroy] do
    collection do
      get :tag_list, action: :list, as: :tag_list
    end
  end
  
  
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.haml
%nav.navbar.bg-dark.border-bottom.border-bottom-dark{"data-bs-theme" => "dark"}
  .container-fluid
    - if user_signed_in?
      = render "home/slide_bar"
    - else
      %h1{style: "margin-left: 20px; color: #FFFFFF"} Training
    - if user_signed_in?
      - if current_user.avatar.attached?
        = image_tag current_user.avatar, size: 100, class: "rounded-circle mr-1", resize: "24x24!"
      - else
        %img.rounded-circle.shadow-4{:alt => "Avatar", :src => "https://www.svgrepo.com/download/5125/avatar.svg", :style => "width: 80px"}/
    - else
      .navbar-buttons
        .button-container
          %div{:style => "display: flex;"}
            = link_to "Librarian Login", new_user_session_path, class: "btn btn-dark"
            = link_to "Student Login", new_student_registration_path, class: "btn btn-dark"

app/views/home/_slide_bar.html.haml
#mySidenav.sidenav
  %a.closebtn{:href => "javascript:void(0)", :onclick => "closeNav()", :style=> "position:absolute; top:0; right:25px; font-size:30px"} ×
  
  - if current_user.librarian?
    %h2.accordion-header
      %button.accordion-button{"aria-controls" => "collapseOne", "aria-expanded" => "false", "data-bs-target" => "#collapseOne", "data-bs-toggle" => "collapse", :type => "button", :style => "color:#FFFFFF"}
        %i.fa.fa-user
          My Profile
    #collapseOne.accordion-collapse.collapse{"data-bs-parent" => "#accordionExample"}
      .accordion-body
        = link_to edit_avatar_path(current_user), class:'btn btn-dark', :style=>"font-size: 15px" do
          Update Avatar
          %end
        = link_to edit_user_path(current_user), class: 'btn btn-dark', :style=>"font-size:15px" do
          Update Personal Data
    %h2.accordion-header
      %button.accordion-button.collapsed{"aria-controls" => "collapseTwo", "aria-expanded"=>"false", "data-bs-target" => "#collapseTwo", "data-bs-toggle"=> "collapse", :type=>"button",:style=>"color:#FFFFFF"}
        %i.fa.fa-book
          Books
    #collapseTwo.accordion-collapse.collapse{"data-bs-parent" => "#accordionExample"}
      .accordion-body
        = link_to book_list_books_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          List of books
        = link_to new_book_path(current_user), class: 'btn btn-dark', :style=>"font-size:15px" do
          Create new book
    %h2.accordion-header
      %button.accordion-button.collapsed{"aria-controls" => "collapseThree", "aria-expanded"=>"false", "data-bs-target" => "#collapseThree", "data-bs-toggle"=> "collapse", :type=>"button",:style=>"color:#FFFFFF"}
        %i.fa.fa-book
          Students
    #collapseThree.accordion-collapse.collapse{"data-bs-parent" => "#accordionExample"}
      .accordion-body
        = link_to student_list_student_index_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          List of students
        = link_to new_student_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Create new student
        = link_to active_student_index_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Active students
        = link_to suspended_student_student_index_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Suspended students
    %h2.accordion-header
      %button.accordion-button.collapsed{"aria-controls" => "collapseFour", "aria-expanded"=>"false", "data-bs-target" => "#collapseFour", "data-bs-toggle"=> "collapse", :type=>"button",:style=>"color:#FFFFFF"}
        %i.fa.fa-book
          Tags
    #collapseFour.accordion-collapse.collapse{"data-bs-parent" => "#accordionExample"}
      .accordion-body
        = link_to new_tag_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Create tags
        = link_to tag_list_tags_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          List of tags
        = link_to active_student_index_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Active students
        = link_to suspended_student_student_index_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Suspended students
    = button_to destroy_user_session_path, class:'btn btn-dark', method: :delete do
      %i.fas.fa-sign-out-alt
        Sign Out
      %end
  - else
    %h2.accordion-header
      %button.accordion-button{"aria-controls" => "collapseOne", "aria-expanded" => "false", "data-bs-target" => "#collapseOne", "data-bs-toggle" => "collapse", :type => "button", :style => "color:#FFFFFF"}
        %i.fa.fa-user
          My Profile
    #collapseOne.accordion-collapse.collapse{"data-bs-parent" => "#accordionExample"}
      .accordion-body
        = link_to edit_avatar_path(current_user), class:'btn btn-dark', :style=>"font-size: 15px" do
          Update Avatar
          %end
        = link_to edit_user_path(current_user), class: 'btn btn-dark', :style=>"font-size:15px" do
          Update Personal Data
    %h2.accordion-header
      %button.accordion-button.collapsed{"aria-controls" => "collapseTwo", "aria-expanded"=>"false", "data-bs-target" => "#collapseTwo", "data-bs-toggle"=> "collapse", :type=>"button",:style=>"color:#FFFFFF"}
        %i.fa.fa-book
          Books
    #collapseTwo.accordion-collapse.collapse{"data-bs-parent" => "#accordionExample"}
      .accordion-body
        = link_to book_list_books_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          List of books
        = link_to root_path(current_user), class: 'btn btn-dark', :style=>"font-size:15px" do
          Available books
        = link_to '/books/issued_list', method: :get,  class: 'btn btn-dark', :style=>"font-size:15px" do
          Issued books
    = button_to destroy_user_session_path, class:'btn btn-dark', method: :delete do
      %i.fas.fa-sign-out-alt
        Sign Out
      %end

%span{:onclick => "openNav()", :style => "font-size:30px;cursor:pointer;color:#FFFFFF"} ☰ Menu
:javascript
  function openNav() {document.getElementById("mySidenav").style.width = "250px";}
  function closeNav() {document.getElementById("mySidenav").style.width = "0";}
  

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.erb
- if user_signed_in?
  %div
    Welcome #{current_user.email}
  = button_to "Sign out", destroy_user_session_path, method: :delete
- else
  = button_to "Sign in", new_user_session_path
  = link_to "Sign up", new_user_registration_path

app/views/home/slide.html.haml
#mySidenav.sidenav
  %a.closebtn{:href => "javascript:void(0)", :onclick => "closeNav()", :style=> "position:absolute; top:0; right:25px; font-size:30px"} ×
  
  %h2.accordion-header
    %button.accordion-button{"aria-controls" => "collapseOne", "aria-expanded" => "false", "data-bs-target" => "#collapseOne", "data-bs-toggle" => "collapse", :type => "button", :style => "color:#FFFFFF"}
      %i.fa.fa-user
        My Profile
  #collapseOne.accordion-collapse.collapse{"data-bs-parent" => "#accordionExample"}
    .accordion-body
      = link_to edit_avatar_path(current_user.id), class:'btn btn-dark', :style=>"font-size: 15px" do
        Update Avatar
        %end
      = link_to edit_user_path(current_user.id), class: 'btn btn-dark', :style=>"font-size:15px" do
        Update Personal Data
  %h2.accordion-header
    %button.accordion-button.collapsed{"aria-controls" => "collapseTwo", "aria-expanded"=>"false", "data-bs-target" => "#collapseTwo", "data-bs-toggle"=> "collapse", :type=>"button",:style=>"color:#FFFFFF"}
      %i.fa.fa-book
        Books
  #collapseTwo.accordion-collapse.collapse{"data-bs-parent" => "#accordionExample"}
    .accordion-body
      - if current_user.librarian?
        = link_to new_book_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Books
        %button.btn.btn-dark{:type=>"button", :href => "#", :style=>"font-size: 15px"} Create new boook
      - else
        = link_to new_book_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          List of books
        = link_to new_book_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Available books
        = link_to new_book_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Issued Books
      %end
  - if current_user.librarian?
    %h2.accordion-header
      %button.accordion-button.collapsed{"aria-controls" => "collapseThree", "aria-expanded"=>"false", "data-bs-target" => "#collapseThree", "data-bs-toggle"=> "collapse", :type=>"button",:style=>"color:#FFFFFF"}
        %i.fas.fa-user-graduate
          Students
    #collapseThree.accordion-collapse.collapse{"data-bs-parent" => "#accordionExample"}
      .accordion-body
        = link_to student_list_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          List of students
        = link_to new_student_path, class: 'btn btn-dark', :style=>"font-size:15px" do
          Add students

  = button_to destroy_user_session_path, class:'btn btn-dark', method: :delete do
    %i.fas.fa-sign-out-alt
      Sign Out
    %end

%span{:onclick => "openNav()", :style => "font-size:30px;cursor:pointer;color:#FFFFFF"} ☰ Menu
:javascript
  function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
  }
  
  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
  }
  