config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  apipie
  get '/home', to: 'home#index', as: 'home'
  root to: redirect('/home')

  resources :avatar, only:[:edit, :update, :destroy]
  resources :users, only:[:edit, :update]
  # resources :books, only:[:new, :create, :show, :destroy]
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get '/student/sign_in', to: 'users/sessions#new'
    post '/student/sign_in', to: 'users/sessions#create', as: 'new_student_registration'
  end

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
  
  # resources :student, only: [:new, :create]
  # resources :tags, only: [:new, :create, :destroy]

  # get '/student_list', to: 'student#list', as: 'student_list'
  # get '/student/active', to: 'student#active', as: 'active'
  # put '/student/:id/suspend', to: 'student#suspend_student', as: 'suspend_student'
  # get '/student/suspended', to: 'student#suspended_student', as: 'suspended_student'
  # post '/student/:id/reactivation', to: 'student#send_reactivation_mail', as: 'send_reactivation_mail'
  # get '/student/:id/reactivate', to: 'student#reactivate_student', as: 'reactivate_student'
  # get '/book_list', to: 'books#list', as: 'book_list'
  # put '/book/:id/archive', to: 'books#archive', as: 'book_archive'
  # get '/tags_list', to: 'tags#list', as: 'tag_list'
  # post '/book/:id/issue', to: 'books#issue', as: 'book_issue'
  # put '/book/:id/like', to: 'books#like', as: 'book_like'
  # get '/book/issued_list', to: 'books#issued_list', as: 'issued_list'
  # put '/book/:id/return', to: 'books#return', as: 'return_book'
  # get 'book/:id/preview', to: 'books#preview', as: 'preview_book'

  resources :student, only: [:new, :create] do
    collection do
      get :student_list, action: :list, as: :student_list
      get :active, action: :active, as: :active
      get :suspended_student, action: :suspended_student, as: :suspended_student
    end
    
    member do
      put :suspend_student, as: :suspend_student
      post :send_reactivation_mail, as: :send_reactivation_mail
      get :reactivate_student, action: :reactivate_student, as: :reactivate_student
    end
  end
  
  resources :books, only: [:new, :create, :show, :destroy] do
    collection do
      get :book_list, action: :list, as: :book_list
      get :issued_list, action: :issued_list, as: :issued_list
    end
  
    member do
      put :archive, as: :archive, as: :book_archive
      post :issue, as: :issue, as: :book_issue
      put :like, as: :like, as: :book_like
      put :return, as: :return, as: :return_book
      get :preview, as: :preview, as: :preview_book
    end
  end
  
  resources :tags, only: [:new, :create, :destroy] do
    collection do
      get :tag_list, action: :list, as: :tag_list
    end
  end
  
  
  
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  include AASM

  aasm column: 'status' do
    state :available, initial: true
    state :not_available
    state :archived
  end

  validates :name, presence: true
  validates :description, presence: true
  validates :number_of_copy, presence: true

  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  has_many :book_users
  has_many :students, class_name: "User", through: :book_users, source: :user

  def available_copy
    number_of_copy - book_users.count
  end

  scope :tagged_with, ->(tag_names){
    joins(:tags).where(tags: {name: tag_names}).group('books.id').having("COUNT(tags.id)>=?", tag_names.size)
  }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def new
        @book=Book.new
    end

    def create
        @book=current_user.books.create(book_params)
        if @book.save
            redirect_to root_path, notice: "Book saved successfully"
        else
            render :new
        end
    end

    def book_params
        params.require(:book).permit(:name, :description, :number_of_copy, tag_ids: [])
    end

    def list
        @book=Book.all

        if current_user.student?
            @book=@book.where.not(status: "archived")
        end

        if params[:tags].present?
            tag_names = params[:tags].split(',').map(&:strip)
            @book=@book.tagged_with(tag_names)
        end

        if params[:filter]=="available"
            @book=@book.where(:status=>"available")
        elsif params[:filter]=="not_available"
            @book=@book.where(:status => "not_available")
        end

        if params[:sort].present?
            sort_column=params[:sort]
            sort_direction= params[:direction] || "desc"
            @book=@book.order("#{sort_column} #{sort_direction}")
        end
        @book=@book.paginate(page: params[:page], per_page: 10)
    end

    def show
        @book=Book.find(params[:id])
    end

    def destroy
        @book=Book.find(params[:id])
        @book.destroy
    end

    def archive
        @book=Book.find(params[:id])
        
        @book.status="archived"
        @book.save
        redirect_to book_path(@book), notice: "Book archived successfully"
    end

    def issue
        @book=Book.find(params[:id])
        if @book.available? && @book.available_copy.positive?
            current_user.issued_books << @book
            if @book.available_copy == @book.number_of_copy
                @book.status="not_available"
                @book.save
            end
            redirect_to book_path(@book) ,notice:"Issued Successfully!"
        end
    end

    def like
        @book=Book.find(params[:id])
        @book.likes ||= 0
        @book.likes+=1
        @book.save
        redirect_to book_path(@book) ,notice:"Book liked"
    end

    def issued_list
        @book=current_user.issued_books
        if params[:sort].present?
            sort_column=params[:sort]
            sort_direction= params[:direction] || "desc"
            @book=@book.order("#{sort_column} #{sort_direction}")
        end
        @book=@book.paginate(page: params[:page], per_page: 10)
    end

    def return
        @book=Book.find(params[:id])
        @book_user = current_user.book_users.find_by(book_id: @book.id)
        @book_user.destroy
        redirect_to book_path(@book) ,notice:"Book returned"
    end

    def preview
        @book=Book.find(params[:id])
        pdf = Prawn::Document.new
        pdf.text 'Ruby on Rails', style: :bold, align: :center, size: 50, color: 'FF0000'
        pdf.move_down 5
        user=User.find(@book.user_id)
        pdf.text "written by: #{user.first_name} #{user.last_name}", align: :center
        pdf.move_down 30
        pdf.text 'Description:', size: 30
        pdf.text " This book is about the #{@book.description}", size: 20
        pdf.move_down 20
        pdf.text "Likes: #{@book.likes}", size: 20
        send_data(pdf.render,
            filename: 'book.pdf',
            type: 'application/pdf', 
            disposition: 'inline')
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/issued_list.html.haml
%br

%center.h1.center Issued Books

%table.table
    %thead.table
        %tr
            %th
                = link_to "Name", :sort => "name", direction: params[:sort] == "name" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Author Name", :sort => "first_name", direction: params[:sort] == "first_name" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Creation Date", :sort => "created_at", direction: params[:sort] == "created_at" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Likes", :sort => "likes", direction: params[:sort] == "likes" && params[:direction] == "asc" ? "desc" : "asc"
            %th
        - @book.each do |book|
            %tr
                %td
                    = link_to book.name, book_path(book)
                %td
                    - user=User.find(book.user_id)
                    = user.first_name
                    = user.last_name
                %td
                    = book.created_at
                %td
                    = book.likes
= will_paginate @book

app/views/books/list.html.haml
%br

%center.h1.center All Books

= form_tag(book_list_books_path, method: :get) do
    %div
        = label_tag "tags", "Search by Tags: "
        = text_field_tag "tags", params[:tags]
        = submit_tag "Search", class: "btn btn-dark"
    %br
    %div
        = label_tag "filter", "Filter by status:"
        = select_tag "filter", options_for_select([["All books", nil], ["Available books", "available"], ["Not available books","not_available"]], params[:filter])
        = submit_tag "Filter", class: "btn btn-dark"

%table.table
    %thead.table
        %tr
            %th
                = link_to "Name", :sort => "name", direction: params[:sort] == "name" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                =  "Author Name"
            %th
                = link_to "Creation Date", :sort => "created_at", direction: params[:sort] == "created_at" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Likes", :sort => "likes", direction: params[:sort] == "likes" && params[:direction] == "asc" ? "desc" : "asc"
            %th
                = link_to "Number of copies", :sort => "number_of_copy", direction: params[:sort] == "number_of_copy" && params[:direction] == "asc" ? "desc" : "asc"
            - if current_user.librarian?
                %th
                    = link_to "Issued copies", :sort => "number_of_copy", direction: params[:sort] == "number_of_copy" && params[:direction] == "asc" ? "desc" : "asc"
            %th
        - @book.each do |book|
            %tr
                %td
                    = link_to book.name, book_path(book)
                %td
                    = book.user.first_name
                    = book.user.last_name
                %td
                    = book.created_at
                %td
                    = book.likes
                %td
                    - if current_user.librarian?
                        = book.number_of_copy
                    - else
                        = book.available_copy
                %td
                    - if current_user.librarian?
                        = book.students.count
= will_paginate @book

app/views/books/new.html.haml
%h3 Add Books
= form_with model: @book, url:books_path(current_user) , modle: :post do |f|
    .field
        = f.label :name
        %br
        = f.text_field :name, autofocus: true, autocomplete: "name"
    .field
        = f.label :description
        %br
        = f.text_field :description, autofocus: true, autocomplete: "description"
    .field
        = f.label :number_of_copy
        %br
        = f.number_field :number_of_copy, autofocus: true, autocomplete: "number_of_copy"
    .field
        = f.label :tags
        %br
        = f.collection_select(:tag_ids, Tag.all, :id, :name, {:prompt=> true}, :multiple=> true, class: "form-control")
    .actions
    = f.submit "Create"

app/views/books/show.html.haml
%h2 Book details
%h4 Book Id: #{@book.id}
%h4 Book Name: #{@book.name}
%h4 Book Description: #{@book.description}
- user=User.find(@book.user_id)
%h4 Author Name: #{user.first_name} #{user.last_name}
%h4 Creation Date: #{@book.created_at.to_date}
%h4 Number of copies: #{@book.number_of_copy}
%h4 Notes: #{@book.note}
%h4 Likes: #{@book.likes}
%h4 Tags:
- @book.tags.each do |tag|
    .li
        = tag.name


= button_to "Issue", book_issue_book_path(@book), method: :post, class: "btn btn-dark"
= button_to "Return", return_book_book_path(@book), method: :put, class: "btn btn-dark"
= button_to "Archive", book_archive_book_path(@book), method: :put, class: "btn btn-dark"
= button_to "Like", book_like_book_path(@book), method: :put, class: "btn btn-dark"
= link_to "Preview", preview_book_book_path(@book), class: "btn btn-dark"
= button_to "Delete", book_path(@book), method: :delete, class: "btn btn-danger"
= link_to "Back", book_list_books_path(@book), class: "btn btn-dark"