config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  apipie
  get '/home', to: 'home#index', as: 'home'
  root to: redirect('/home')

  resources :avatar, only:[:edit, :update, :destroy]
  resources :users, only:[:edit, :update]
  # resources :books, only:[:new, :create, :show, :destroy]
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get '/student/sign_in', to: 'users/sessions#new'
    post '/student/sign_in', to: 'users/sessions#create', as: 'new_student_registration'
  end

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
  
  # resources :student, only: [:new, :create]
  # resources :tags, only: [:new, :create, :destroy]

  # get '/student_list', to: 'student#list', as: 'student_list'
  # get '/student/active', to: 'student#active', as: 'active'
  # put '/student/:id/suspend', to: 'student#suspend_student', as: 'suspend_student'
  # get '/student/suspended', to: 'student#suspended_student', as: 'suspended_student'
  # post '/student/:id/reactivation', to: 'student#send_reactivation_mail', as: 'send_reactivation_mail'
  # get '/student/:id/reactivate', to: 'student#reactivate_student', as: 'reactivate_student'
  # get '/book_list', to: 'books#list', as: 'book_list'
  # put '/book/:id/archive', to: 'books#archive', as: 'book_archive'
  # get '/tags_list', to: 'tags#list', as: 'tag_list'
  # post '/book/:id/issue', to: 'books#issue', as: 'book_issue'
  # put '/book/:id/like', to: 'books#like', as: 'book_like'
  # get '/book/issued_list', to: 'books#issued_list', as: 'issued_list'
  # put '/book/:id/return', to: 'books#return', as: 'return_book'
  # get 'book/:id/preview', to: 'books#preview', as: 'preview_book'

  resources :student, only: [:new, :create] do
    collection do
      get :student_list, action: :list, as: :student_list
      get :active, action: :active, as: :active
      get :suspended_student, action: :suspended_student, as: :suspended_student
    end
    
    member do
      put :suspend_student, as: :suspend_student
      post :send_reactivation_mail, as: :send_reactivation_mail
      get :reactivate_student, action: :reactivate_student, as: :reactivate_student
    end
  end
  
  resources :books, only: [:new, :create, :show, :destroy] do
    collection do
      get :book_list, action: :list, as: :book_list
      get :issued_list, action: :issued_list, as: :issued_list
    end
  
    member do
      put :archive, as: :archive, as: :book_archive
      post :issue, as: :issue, as: :book_issue
      put :like, as: :like, as: :book_like
      put :return, as: :return, as: :return_book
      get :preview, as: :preview, as: :preview_book
    end
  end
  
  resources :tags, only: [:new, :create, :destroy] do
    collection do
      get :tag_list, action: :list, as: :tag_list
    end
  end
  
  
  
  
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :book_tags, dependent: :destroy
    has_many :books, through: :book_tags

    validates :name, presence: true

    before_destroy :check_books

    private
    def check_books
        return false if books.any?
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def new
        @tag=Tag.new
    end

    def create
        @tag=Tag.new(tag_params)
        if @tag.save
            redirect_to root_path, notice: "Tag created successfully"
        else
            render :new
        end
    end

    def tag_params
        params.require(:tag).permit(:name)
    end

    def list
        @tag=Tag.all
        if params[:sort].present?
            sort_column=params[:sort]
            sort_direction= params[:direction] || "desc"
            @tag=@tag.order("#{sort_column} #{sort_direction}")
        end
        @tag=@tag.paginate(page: params[:page], per_page: 10)
    end

    def destroy
        @tag=Tag.find(params[:id])
        @tag.destroy
        redirect_to tag_list_tags_path, notice: "Tag deleted successfully"
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/list.html.haml
%br

%center.h1.center All Tags

%table.table.m-5
  %thead.table
    %tr
      %th= link_to "Id", :sort => "id", direction: params[:sort] == "id" && params[:direction] == "asc" ? "desc" : "asc"
      %th= link_to "Name", :sort => "name", direction: params[:sort] == "first_name" && params[:direction] == "asc" ? "desc" : "asc"
      %th= link_to "Creation Date", :sort => "created_at", direction: params[:sort] == "created_at" && params[:direction] == "asc" ? "desc" : "asc"
      %th= link_to "Last Update Date", :sort => "updated_at", direction: params[:sort] == "updated_at" && params[:direction] == "asc" ? "desc" : "asc"
      %th= link_to "Number of books", :sort => "number_of_books", direction: params[:sort] == "number_of_books" && params[:direction] == "asc" ? "desc" : "asc"
      

  - @tag.each do |tag|
    %tr
      %td= tag.id
      %td= tag.name
      %td= tag.created_at
      %td= tag.updated_at
      %td= tag.books.count
      %td
        - if tag.books.count <= 0
          = button_to "Delete", tag_path(tag), method: :delete, class: "btn btn-danger"

= will_paginate @tag

app/views/tags/new.html.haml
= form_with model: @tag, url: tags_path, method: :post do |f|
    .field
        = f.label :name
        %br/
        = f.text_field :name, autofocus: true
    .action
        = f.submit "Create"